In [91]:
import numpy as np
import pandas as pd

df = pd.read_excel('Book2.xlsx')

arr = df.to_numpy()
X = (arr[: , 0])
Y = (arr[: , 1])
m = len(X)
X = np.reshape(X , (len(X),1))
Y = np.reshape(Y ,(len(X) ,1) )
X = (X - 18)/(62-18)
X = np.c_[np.ones((len(X),1)),X]
#Y = (Y -9854)/(80679 -9854)
m=len(X)

rate = 0.723

iter = 1000
theta_best = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(Y)
print("theta by analytical method : " , theta_best.T)
#theta = np.random.randn(2,1)
theta = np.array ([[0], [0]])
for i in range(iter):        
         prediction = np.dot(X,theta)
        # print(prediction)
         theta = theta -(rate/len(X))*( np.dot(X.T , (prediction - Y)))
        # print(theta.T)
print(theta , rate)

theta by analytical method :  [[0.00536652 1.04209329]]
[[0.00536652]
 [1.04209329]] 0.723

In [92]:

rr = np.dot(X,theta)
rr

array([[0.10010227],
       [0.17115409],
       [0.69220073],
       [0.81062042],
       [0.66851679],
       [0.90535618],
       [0.88167224],
       [1.00009193],
       [1.04745981],
       [1.02377587],
       [0.00536652],
       [0.2422059 ],
       [0.21852197],
       [0.26588984],
       [0.73956861],
       [0.88167224],
       [0.17115409],
       [0.95272406],
       [0.02905046],
       [0.00536652],
       [0.07641834],
       [0.19483803],
       [0.52641316],
       [0.64483286],
       [0.76325255],
       [0.8579883 ],
       [0.12378621]])

In [93]:
sig = 1/(1+(np.exp(-rr)))
sig = sig - 0.119469 +0.5

In [94]:
df['predicted'] = np.floor(sig)
df

    age  insurance  predicted
0    22          0        0.0
1    25          0        0.0
2    47          1        1.0
3    52          0        1.0
4    46          1        1.0
5    56          1        1.0
6    55          0        1.0
7    60          1        1.0
8    62          1        1.0
9    61          1        1.0
10   18          0        0.0
11   28          0        0.0
12   27          0        0.0
13   29          0        0.0
14   49          1        1.0
15   55          1        1.0
16   25          1        0.0
17   58          1        1.0
18   19          0        0.0
19   18          0        0.0
20   21          0        0.0
21   26          0        0.0
22   40          1        1.0
23   45          1        1.0
24   50          1        1.0
25   54          1        1.0
26   23          0        0.0